---
title: "Round Data Performance"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}

```

## West UDP Jitter

Round 1, Round 05, Round 10, Round 12 Data comparisons

```{r pressure, echo=FALSE}
  library(ggplot2)
  mydata = read.csv("https://raw.githubusercontent.com/CSUMB-CST499-S18/udp-mobile-analysis/master/Cumulative_Round10_Results_Final.csv")
  par(mfrow=c(1,4))
  
  getavgWest<-function(x,sdata){
    y<-nrow(sdata)*(x/100)
    #print(y)
    y<-round(y, digits = 0)
    
    newdata<-sdata[1:y,]
    sumnewdata<-sum(newdata$jitterCol)
    #print(sumnewdata)
    avgNewData<-sumnewdata/y
    #avgNewData<-round(avgNewData, digits = 0)
    return(avgNewData)
  }
  plotRoundData = function(x1, x2, x3, x4, provider, type, round_01_data, round_05_data, round_10_data, round_12_data)
  {
    #View(mydatafiltered)
    #Convert the errors to INF
    jitterCol="jitterCol"
    
    mydatafiltered = round_12_data[c(1:8,12,18:53)]
    names(mydatafiltered)[x1]<-jitterCol
    mydatafiltered = na.omit(mydatafiltered)
    mydatafiltered$jitterCol  <- gsub("^[a-z].*", -1, mydatafiltered$jitterCol)
   #mean(as.numeric(as.character(mydatafiltered$jitterCol)))
    mydatafiltered$jitterCol  <- gsub(-1,sum(as.numeric(as.character(mydatafiltered$jitterCol[mydatafiltered$jitterCol > 0])))/ length(as.numeric(as.character(mydatafiltered$jitterCol[mydatafiltered$jitterCol > 0]))), mydatafiltered$jitterCol)
    #convert char to numeric 
    mydatafiltered$jitterCol <- as.numeric(as.character(mydatafiltered$jitterCol))
    mydat<-mydatafiltered[mydatafiltered$DeviceType == "Phone",]
  
    
    #Sprint
    round12<-mydat[mydat$Provider == provider,]
    round12_sorted<-round12[order(round12$jitterCol),]
    #################################################################################################
       
    mydatafiltered = round_10_data[c(1:8,12,18:53)]
    names(mydatafiltered)[x2]<-jitterCol
    mydatafiltered = na.omit(mydatafiltered)
    mydatafiltered$jitterCol  <- gsub("^[a-z].*", -1, mydatafiltered$jitterCol)
   #mean(as.numeric(as.character(mydatafiltered$jitterCol)))
    mydatafiltered$jitterCol  <- gsub(-1,sum(as.numeric(as.character(mydatafiltered$jitterCol[mydatafiltered$jitterCol > 0])))/ length(as.numeric(as.character(mydatafiltered$jitterCol[mydatafiltered$jitterCol > 0]))), mydatafiltered$jitterCol)
    #convert char to numeric 
    mydatafiltered$jitterCol <- as.numeric(as.character(mydatafiltered$jitterCol))
    mydat<-mydatafiltered[mydatafiltered$DeviceType == "Phone",]
    
    #round10
    round10<-mydat[mydat$Provider == provider,]
    round10_sorted<-round10[order(round10$jitterCol),]
    ##############################################################################################
   
    mydatafiltered = round_05_data[c(1:9,15:53)]
    names(mydatafiltered)[x3]<-jitterCol
    mydatafiltered = na.omit(mydatafiltered)
    mydatafiltered$jitterCol  <- gsub("^[a-z].*", -1, mydatafiltered$jitterCol)
   #mean(as.numeric(as.character(mydatafiltered$jitterCol)))
    mydatafiltered$jitterCol  <- gsub(-1,sum(as.numeric(as.character(mydatafiltered$jitterCol[mydatafiltered$jitterCol > 0])))/ length(as.numeric(as.character(mydatafiltered$jitterCol[mydatafiltered$jitterCol > 0]))), mydatafiltered$jitterCol)
    #convert char to numeric 
    mydatafiltered = na.omit(mydatafiltered)

    mydatafiltered$jitterCol <- as.numeric(as.character(mydatafiltered$jitterCol))
    mydatafiltered = na.omit(mydatafiltered)

    mydat<-mydatafiltered[mydatafiltered$Client_Type == " Phone",]
    
    #round10
    round05<-mydat[mydat$Provider == paste0(" ", provider),]
    round05_sorted<-round05[order(round05$jitterCol),]
    
    ##############################################################################################
  
    mydatafiltered = round_01_data[c(1:8,15:53)]
    names(mydatafiltered)[x4]<-jitterCol
    mydatafiltered = na.omit(mydatafiltered)
    mydatafiltered$jitterCol  <- gsub("^[a-z].*", -1, mydatafiltered$jitterCol)
   #mean(as.numeric(as.character(mydatafiltered$jitterCol)))
    mydatafiltered$jitterCol  <-     gsub(-1,sum(as.numeric(as.character(mydatafiltered$jitterCol[mydatafiltered$jitterCol > 0])))/ length(as.numeric(as.character(mydatafiltered$jitterCol[mydatafiltered$jitterCol > 0]))), mydatafiltered$jitterCol)
    #convert char to numeric 
    mydatafiltered$jitterCol <- as.numeric(as.character(mydatafiltered$jitterCol))
        mydatafiltered = na.omit(mydatafiltered)

    mydat<-mydatafiltered[mydatafiltered$Client.Type == " Phone",]
    #round01
    round01<-mydat[mydat$Provider == provider,]
    round01_sorted<-round01[order(round01$jitterCol),]
    #Round 10
    r_10 = c()
    for(i in 1:100)
    #for(i in 1:10)
    {
      r_10<-c(r_10,getavgWest(i,round10_sorted))
    }
    
    #Round 12
    r_12 =c()
    for(i in 1:100)
    {
      r_12<-c(r_12,getavgWest(i,round12_sorted))
    }
    r_05 =c()
    for(i in 1:100)
    {
      r_05<-c(r_05,getavgWest(i,round05_sorted))
    }
    r_01 =c()
    for(i in 1:100)
    {
      r_01<-c(r_01,getavgWest(i,round01_sorted))
    }
    #####################################################################################
    percent = c()
    for(i in 1:100)
    {
      percent<-c(percent,i)
    }
    percent
    west=c()
    west<-cbind(percent,r_01,r_05,r_10,r_12)
    
    west <- transform(west,  percent = as.numeric(percent), 
                      r_10 = as.numeric(r_10), 
                      r_12 = as.numeric(r_12),
                      r_05 = as.numeric(r_05),
                      r_01 = as.numeric(r_01))
    
    west
    jitters=c("wUDPJit1", "wUDPJit2", "wUDPJit3", "wUDPJit4")
    names(jitters) = c("22","25","28","40")
    jittersEast = c("eUDPJit1","eUDPJit2", "eUDPJit3", "eUDPJit4")
    names(jittersEast) = c("31", "34", "37", "43")
    if(type == "eUDPLoss") {
      ggplot(west, aes(percent)) + 
       geom_line(aes(y = r_01, colour = "Round 01"), linetype = "solid", size = 1) +
        geom_line(aes(y = r_05, colour = "Round 05"), linetype = "solid", size = .90) +
        geom_line(aes(y = r_12, colour = "Round 12"), linetype = "solid", size = .80) +
        geom_line(aes(y = r_10, colour = "Round 10"), linetype = "solid", size = .70) +
        scale_x_continuous(name="Percentage (%)", limits=c(0, 100)) +
        scale_y_continuous(name="East Average Loss (Milliseconds)") +
        ggtitle(paste("East Phone", provider, sep = " "))
    } else if(type == "eUDPJit") {
      ggplot(west, aes(percent)) + 
       geom_line(aes(y = r_01, colour = "Round 01"), linetype = "solid", size = 1) +
        geom_line(aes(y = r_05, colour = "Round 05"), linetype = "solid", size = .90) +
        geom_line(aes(y = r_12, colour = "Round 12"), linetype = "solid", size = .80) +
        geom_line(aes(y = r_10, colour = "Round 10"), linetype = "solid", size = .70) +
        scale_x_continuous(name="Percentage (%)", limits=c(0, 100)) +
        scale_y_continuous(name="East Average Jitter[(Milliseconds)") +
        ggtitle(paste("East Phone", provider, sep = " "))
    } else if(type == "wUDPJit") {
      ggplot(west, aes(percent)) + 
        geom_line(aes(y = r_01, colour = "Round 01"), linetype = "solid", size = 1) +
        geom_line(aes(y = r_05, colour = "Round 05"), linetype = "solid", size = .90) +
        geom_line(aes(y = r_12, colour = "Round 12"), linetype = "solid", size = .80) +
        geom_line(aes(y = r_10, colour = "Round 10"), linetype = "solid", size = .70) +
        scale_x_continuous(name="Percentage (%)", limits=c(0, 100)) +
        scale_y_continuous(name="West Average Jitterjitters (Milliseconds)") +
        ggtitle(paste("West Phone", provider, sep = " "))
      
    }
    else if(type == "wUDPLoss") {
      ggplot(west, aes(percent)) + 
       geom_line(aes(y = r_01, colour = "Round 01"), linetype = "solid", size = 1) +
        geom_line(aes(y = r_05, colour = "Round 05"), linetype = "solid", size = .90) +
        geom_line(aes(y = r_12, colour = "Round 12"), linetype = "solid", size = .80) +
        geom_line(aes(y = r_10, colour = "Round 10"), linetype = "solid", size = .70) +
        scale_x_continuous(name="Percentage (%)", limits=c(0, 100)) +
        scale_y_continuous(name= "West Average Loss (Milliseconds)") +
        ggtitle(paste("West Phone", provider, sep = " "))
    }
    else if(type == "wRttAvg") {
       ggplot(west, aes(percent)) +
        geom_line(aes(y = r_01, colour = "Round 01"), linetype = "solid", size = 1) +
        geom_line(aes(y = r_05, colour = "Round 05"), linetype = "solid", size = .90) +
        geom_line(aes(y = r_12, colour = "Round 12"), linetype = "solid", size = .80) +
        geom_line(aes(y = r_10, colour = "Round 10"), linetype = "solid", size = .70) +
        scale_x_continuous(name="Percentage (%)", limits=c(0, 100)) +
        scale_y_continuous(name="West Average Loss (Milliseconds)") +
        ggtitle(paste("West Phone", provider, sep = " "))
    }
    else if(type == "eRttAvg") {
      ggplot(west, aes(percent)) + 
       geom_line(aes(y = r_01, colour = "Round 01"), linetype = "solid", size = 1) +
        geom_line(aes(y = r_05, colour = "Round 05"), linetype = "solid", size = .90) +
        geom_line(aes(y = r_12, colour = "Round 12"), linetype = "solid", size = .80) +
        geom_line(aes(y = r_10, colour = "Round 10"), linetype = "solid", size = .70) +
        scale_x_continuous(name="Percentage (%)", limits=c(0, 100)) +
        scale_y_continuous(name= "East Average RTT (Milliseconds)") +
        ggtitle(paste("East Phone", provider, sep = " "))
    }
  
   
  }
  par(mfrow=c(4,1))
  #Example: plotJitter(x)
  # x = column number for column to plot
  #west
  #plotRoundData(16, 16, 17, 16, "Sprint", "wRttAvg")
  round_01_data = read.csv("https://raw.githubusercontent.com/CSUMB-CST499-S18/udp-mobile-analysis/jitter/Cumulative_Round01_Results_Final.csv", na.strings = c("NA", "N/A"))
   round_05_data = read.csv("https://raw.githubusercontent.com/CSUMB-CST499-S18/udp-mobile-analysis/jitter/Cumulative_Round05_Results_Final.csv", na.strings = c("NA", "N/A"))
    round_10_data = read.csv("https://raw.githubusercontent.com/CSUMB-CST499-S18/udp-mobile-analysis/tcpAndUdpComparison/Cumulative_Round10_Results_Final.csv", na.strings = c("NA", "N/A"))
    round_12_data = read.csv("https://raw.githubusercontent.com/CSUMB-CST499-S18/udp-mobile-analysis/tcpAndUdpComparison/Round12/Cumulative_Round12_Results_Final.csv", na.strings = c("NA", "N/A"))

  plotRoundData(22, 22, 19, 18, "Sprint", "wUDPJit", round_01_data, round_05_data, round_10_data, round_12_data)
  plotRoundData(22, 22, 19, 18, "Verizon", "wUDPJit", round_01_data, round_05_data, round_10_data, round_12_data)
  plotRoundData(22, 22, 19, 18, "AT&T", "wUDPJit", round_01_data, round_05_data, round_10_data, round_12_data)
  plotRoundData(22, 22, 19, 18, "T-Mobile", "wUDPJit", round_01_data, round_05_data, round_10_data, round_12_data)

```


## East UDP Jitter

Round 1, Round 05, Round 10, Round 12 Data comparisons
```{r}
  plotRoundData(31, 31, 28, 27, "Sprint", "eUDPJit", round_01_data, round_05_data, round_10_data, round_12_data)
  plotRoundData(31, 31, 28, 27, "Verizon", "eUDPJit", round_01_data, round_05_data, round_10_data, round_12_data)
  plotRoundData(31, 31, 28, 27, "AT&T", "eUDPJit", round_01_data, round_05_data, round_10_data, round_12_data)
  plotRoundData(31, 31, 28, 27, "T-Mobile", "eUDPJit", round_01_data, round_05_data, round_10_data, round_12_data)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
